import { useEffect, useState } from "react";
import {
  fetchStudentDashboard,
  savePaidInternshipProjectDetails,
  studentDocumentUrl,
  uploadCompletedDocuments,
} from "../services/studentService";
import {
  clearStudentSession,
  getStudentSession,
} from "../services/studentSession";
import { authHeader, handleUnauthorized } from "../services/authSession";
import { usePresignAndOpen } from "../utils/presignedFile";
import "../styles/admin.css";

function formatDate(value) {
  if (!value) return "-";
  return new Date(value).toLocaleDateString("en-IN");
}

function DetailGrid({ title, rows }) {
  return (
    <section className="details-section">
      <h2>{title}</h2>
      <div className="details-grid">
        {rows.map(([label, value]) => (
          <div className="detail-item" key={label}>
            <span>{label}</span>
            <strong>{value || "-"}</strong>
          </div>
        ))}
      </div>
    </section>
  );
}

// For R2-backed files (photo, resume, offer letter, etc.) - resolves a
// presigned URL at click time and opens it in a new tab.
function FileLink({ label, href }) {
  const { open, busy, error } = usePresignAndOpen("student");
  if (!href) return null;

  return (
    <>
      <button
        type="button"
        className="student-document-link"
        onClick={() => open(href)}
        disabled={busy}
      >
        {busy ? "Opening…" : label}
      </button>
      {error && <span className="admin-error">{error}</span>}
    </>
  );
}

// Declaration/character certificate forms are generated by the backend on
// request - there's no R2 object behind them, so this hits our own API
// directly with the student's Bearer token, not the presign endpoint.
function DownloadFormLink({ label, href, filename }) {
  const [error, setError] = useState("");

  if (!href) return null;

  const handleClick = async (e) => {
    e.preventDefault();
    setError("");
    try {
      const response = await fetch(href, { headers: authHeader("student") });
      if (response.status === 401) handleUnauthorized("student");
      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        throw new Error(body.message || "Download failed.");
      }
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = filename;
      link.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      setError(err.message || "Download failed.");
    }
  };

  return (
    <>
      <a className="student-document-link" href={href} onClick={handleClick} rel="noreferrer">
        {label}
      </a>
      {error && <span className="admin-error">{error}</span>}
    </>
  );
}

function StudentDashboard() {
  const [student, setStudent] = useState(null);
  const [token] = useState(getStudentSession());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [completedFile, setCompletedFile] = useState(null);
  const [uploadMessage, setUploadMessage] = useState("");
  const [projectDetails, setProjectDetails] = useState(null);
  const [projectDetailsMessage, setProjectDetailsMessage] = useState("");
  const [savingProjectDetails, setSavingProjectDetails] = useState(false);
  const [bankDetails, setBankDetails] = useState({ bankName: "", savingAccountNumber: "", ifsc: "" });
  const [firstQuarterReport, setFirstQuarterReport] = useState({ fromDate: "", toDate: "", daysPresent: "" });
  const [secondQuarterReport, setSecondQuarterReport] = useState({ fromDate: "", toDate: "", daysPresent: "" });
  const [savingBankDetails, setSavingBankDetails] = useState(false);
  const [bankDetailsMessage, setBankDetailsMessage] = useState("");
  const [savingFirstQuarter, setSavingFirstQuarter] = useState(false);
  const [firstQuarterMessage, setFirstQuarterMessage] = useState("");
  const [savingSecondQuarter, setSavingSecondQuarter] = useState(false);
  const [secondQuarterMessage, setSecondQuarterMessage] = useState("");

  useEffect(() => {
    if (!token) {
      window.history.replaceState({}, "", "/student/login");
      window.dispatchEvent(new PopStateEvent("popstate"));
      return;
    }

    let ignore = false;

    async function loadDashboard() {
      try {
        const response = await fetchStudentDashboard();
        if (!ignore) {
          setStudent(response.student);
          setProjectDetails(response.student.paidInternshipProjectDetails || {
            projectName: "", designationTitle: "", supervisorName: "", projectNameAndPdc: "", achievements: "",
          });
          setBankDetails(response.student.bankDetails || { bankName: "", savingAccountNumber: "", ifsc: "" });
          setFirstQuarterReport(response.student.firstQuarterReport || { fromDate: "", toDate: "", daysPresent: "" });
          setSecondQuarterReport(response.student.secondQuarterReport || { fromDate: "", toDate: "", daysPresent: "" });
        }
      } catch (err) {
        if (!ignore) setError(err.message);
      } finally {
        if (!ignore) setLoading(false);
      }
    }

    loadDashboard();

    return () => {
      ignore = true;
    };
  }, [token]);

  const logout = () => {
    clearStudentSession();
    window.history.pushState({}, "", "/student/login");
    window.dispatchEvent(new PopStateEvent("popstate"));
  };

  const handleCompletedUpload = async (event) => {
    event.preventDefault();
    setUploadMessage("");

    if (!completedFile) {
      setUploadMessage("Select Upload Form 1 and Form 2 (Single PDF).");
      return;
    }
    if (completedFile.size > 10 * 1024 * 1024) {
      setUploadMessage("Maximum file size allowed is 10 MB.");
      return;
    }

    try {
      const response = await uploadCompletedDocuments(completedFile);
      setStudent(response.student);
      setUploadMessage(response.message);
    } catch (err) {
      setUploadMessage(err.message);
    }
  };

  const handleProjectDetailsSave = async (event) => {
    event.preventDefault();
    setSavingProjectDetails(true);
    setProjectDetailsMessage("");
    try {
      const response = await savePaidInternshipProjectDetails(projectDetails);
      setStudent(response.student);
      setProjectDetails(response.student.paidInternshipProjectDetails);
      setProjectDetailsMessage(response.message);
    } catch (err) {
      setProjectDetailsMessage(err.message);
    } finally {
      setSavingProjectDetails(false);
    }
  };

  const handleBankDetailsSave = async (event) => {
    event.preventDefault();
    setSavingBankDetails(true);
    setBankDetailsMessage("");
    if (bankDetails.savingAccountNumber && !/^\d+$/.test(bankDetails.savingAccountNumber)) {
      setBankDetailsMessage("Saving Account Number must contain digits only.");
      setSavingBankDetails(false);
      return;
    }
    if (bankDetails.ifsc && !/^[A-Z]{4}0[A-Z0-9]{6}$/i.test(bankDetails.ifsc)) {
      setBankDetailsMessage("Enter a valid 11-digit IFSC code (e.g. SBIN0001234).");
      setSavingBankDetails(false);
      return;
    }
    try {
      const response = await savePaidInternshipProjectDetails({ bankDetails });
      setStudent(response.student);
      setBankDetails(response.student.bankDetails || { bankName: "", savingAccountNumber: "", ifsc: "" });
      setBankDetailsMessage("Bank details saved successfully.");
    } catch (err) {
      setBankDetailsMessage(err.message);
    } finally {
      setSavingBankDetails(false);
    }
  };

  const handleFirstQuarterSave = async (event) => {
    event.preventDefault();
    setSavingFirstQuarter(true);
    setFirstQuarterMessage("");
    const { fromDate, toDate, daysPresent } = firstQuarterReport;
    if (fromDate && toDate) {
      const start = new Date(fromDate);
      const end = new Date(toDate);
      if (end < start) {
        setFirstQuarterMessage("To Date cannot be earlier than From Date.");
        setSavingFirstQuarter(false);
        return;
      }
      const diffDays = Math.round((end - start) / (1000 * 60 * 60 * 24));
      if (diffDays > 95) {
        setFirstQuarterMessage("First Quarter Report: Date range must not exceed 95 days.");
        setSavingFirstQuarter(false);
        return;
      }
    }
    if (daysPresent !== undefined && daysPresent !== "") {
      const days = Number(daysPresent);
      if (!Number.isSafeInteger(days) || days < 0) {
        setFirstQuarterMessage("Days Present must be a non-negative whole number.");
        setSavingFirstQuarter(false);
        return;
      }
    }
    try {
      const response = await savePaidInternshipProjectDetails({ firstQuarterReport });
      setStudent(response.student);
      setFirstQuarterReport(response.student.firstQuarterReport || { fromDate: "", toDate: "", daysPresent: "" });
      setFirstQuarterMessage("First Quarter Report saved successfully.");
    } catch (err) {
      setFirstQuarterMessage(err.message);
    } finally {
      setSavingFirstQuarter(false);
    }
  };

  const handleSecondQuarterSave = async (event) => {
    event.preventDefault();
    setSavingSecondQuarter(true);
    setSecondQuarterMessage("");
    const { fromDate, toDate, daysPresent } = secondQuarterReport;
    if (fromDate && toDate) {
      const start = new Date(fromDate);
      const end = new Date(toDate);
      if (end < start) {
        setSecondQuarterMessage("To Date cannot be earlier than From Date.");
        setSavingSecondQuarter(false);
        return;
      }
      const diffDays = Math.round((end - start) / (1000 * 60 * 60 * 24));
      if (diffDays > 95) {
        setSecondQuarterMessage("Second Quarter Report: Date range must not exceed 95 days.");
        setSavingSecondQuarter(false);
        return;
      }
    }
    if (daysPresent !== undefined && daysPresent !== "") {
      const days = Number(daysPresent);
      if (!Number.isSafeInteger(days) || days < 0) {
        setSecondQuarterMessage("Days Present must be a non-negative whole number.");
        setSavingSecondQuarter(false);
        return;
      }
    }
    try {
      const response = await savePaidInternshipProjectDetails({ secondQuarterReport });
      setStudent(response.student);
      setSecondQuarterReport(response.student.secondQuarterReport || { fromDate: "", toDate: "", daysPresent: "" });
      setSecondQuarterMessage("Second Quarter Report saved successfully.");
    } catch (err) {
      setSecondQuarterMessage(err.message);
    } finally {
      setSavingSecondQuarter(false);
    }
  };

  if (loading) {
    return (
      <main className="admin-shell">
        <div className="admin-loading">Loading student dashboard...</div>
      </main>
    );
  }

  if (error || !student) {
    return (
      <main className="admin-shell">
        <button className="secondary-button" type="button" onClick={logout}>
          Back to Login
        </button>
        <p className="admin-error">{error || "Student record not found."}</p>
      </main>
    );
  }
  const approved = student.status === "Approved";

  return (
    <main className="admin-shell">
      <header className="admin-topbar">
        <div>
          <p className="portal-eyebrow">Student Dashboard</p>
          <h1>{student.name}</h1>
          <div className="student-info-box">
            <div className="student-info-item">
              <span className="student-info-label">Email: </span>
              <strong>{student.email}</strong>
            </div>

            <div className="student-info-item">
              <span className="student-info-label">Application ID: </span>
              <strong>{student.referenceId}</strong>
            </div>
          </div>
        </div>
        <button className="secondary-button" type="button" onClick={logout}>
          Logout
        </button>
      </header>

      <DetailGrid
        title="Personal Details"
        rows={[
          ["Name", student.name],
          ["Email", student.email],
          ["Phone Number", student.phone],
          ["Gender", student.gender],
          ["Date of Birth", student.dob],
          ["Application Status", student.status],
        ]}
      />

      <DetailGrid
        title="Academic Details"
        rows={[
          ["Course", student.course],
          ["Branch", student.branch],
          ["Year", student.year],
          ["CGPA", student.cgpa],
          ["College Name", student.collegeName],
          ["College Location", student.location],
        ]}
      />

      <DetailGrid
        title="Parent Details"
        rows={[
          ["Father's Name", student.fatherName],
          ["Parent's Contact Number", student.fatherPhone],
          ["Parent's Occupation", student.fatherOccupation],
        ]}
      />

      <DetailGrid
        title="Internship Details"
        rows={[
          ["Training Duration", student.internshipDuration],
          ["Joining Month", student.internshipJoiningMonth],
          ["Submitted On", formatDate(student.submittedAt)],
          ["Remark", student.remark],
        ]}
      />

      <section className="details-section">
        <h2>Student Documents</h2>
        <div className="document-actions">
          <FileLink label="View Photo" href={student.photo?.url} />
          <FileLink label="View Curriculum Vitae" href={student.resume?.url} />
          <FileLink label="View Marksheet" href={student.result?.url} />
          <FileLink
            label="View College Referral Letter"
            href={student.permissionLetter?.url}
          />
          <FileLink label="View Aadhaar Card" href={student.aadhaarCard?.url} />
        </div>
      </section>

      <section className="details-section">
        <h2>Documents to be Filled by Students</h2>
        {approved ? (
          <div className="document-actions">
            <FileLink
              label="View Offer Letter"
              href={student.offerLetter?.url || student.offerLetterUrl}
            />
            <DownloadFormLink
              label="Download Declaration Form (Form 1)"
              href={studentDocumentUrl("declaration")}
              filename="Declaration-Form.pdf"
            />
            <DownloadFormLink
              label="Download Character Certificate (Form 2)"
              href={studentDocumentUrl("character")}
              filename="Character-Certificate.pdf"
            />
          </div>
        ) : (
          <p className="admin-muted">
            Documents to be filled become available after your application is
            approved.
          </p>
        )}
      </section>

      {approved && student.internshipType === "Paid" && projectDetails && (
        <>
          <section className="details-section">
            <h2>Paid Internship Project Details</h2>
            <p className="admin-muted">All fields are optional and can be updated later.</p>
            <form className="training-form" onSubmit={handleProjectDetailsSave}>
              {[
                ["projectName", "Name of Project"],
                ["designationTitle", "Title of Assignment"],
                ["supervisorName", "Name of Supervisor"],
                ["projectNameAndPdc", "Name & PDC of the Project in which Working"],
                ["achievements", "Achievements"],
              ].map(([name, label]) => (
                <label className="admin-field" key={name}>
                  <span>{label}</span>
                  <input name={name} value={projectDetails[name] || ""} onChange={(event) => setProjectDetails(current => ({ ...current, [name]: event.target.value }))} />
                </label>
              ))}
              <button className="primary-button" type="submit" disabled={savingProjectDetails}>{savingProjectDetails ? "Saving..." : "Save Project Details"}</button>
            </form>
            {projectDetailsMessage && <p className={projectDetailsMessage.includes("successfully") ? "admin-muted" : "admin-error"}>{projectDetailsMessage}</p>}
          </section>

          <section className="details-section">
            <h2>Bank Details</h2>
            <p className="admin-muted">All fields are optional and can be updated later.</p>
            <form className="training-form" onSubmit={handleBankDetailsSave}>
              <label className="admin-field">
                <span>Bank Name</span>
                <input value={bankDetails.bankName || ""} onChange={(event) => setBankDetails(current => ({ ...current, bankName: event.target.value }))} />
              </label>
              <label className="admin-field">
                <span>Saving A/c No.</span>
                <input value={bankDetails.savingAccountNumber || ""} onChange={(event) => setBankDetails(current => ({ ...current, savingAccountNumber: event.target.value }))} />
              </label>
              <label className="admin-field">
                <span>IFSC</span>
                <input value={bankDetails.ifsc || ""} onChange={(event) => setBankDetails(current => ({ ...current, ifsc: event.target.value }))} />
              </label>
              <button className="primary-button" type="submit" disabled={savingBankDetails}>{savingBankDetails ? "Saving..." : "Save Bank Details"}</button>
            </form>
            {bankDetailsMessage && <p className={bankDetailsMessage.includes("successfully") ? "admin-muted" : "admin-error"}>{bankDetailsMessage}</p>}
          </section>

          <section className="details-section">
            <h2>First Quarter Report</h2>
            <form className="training-form" onSubmit={handleFirstQuarterSave}>
              <label className="admin-field">
                <span>From Date</span>
                <input type="date" value={firstQuarterReport.fromDate ? firstQuarterReport.fromDate.slice(0, 10) : ""} onChange={(event) => setFirstQuarterReport(current => ({ ...current, fromDate: event.target.value }))} />
              </label>
              <label className="admin-field">
                <span>To Date</span>
                <input type="date" value={firstQuarterReport.toDate ? firstQuarterReport.toDate.slice(0, 10) : ""} onChange={(event) => setFirstQuarterReport(current => ({ ...current, toDate: event.target.value }))} />
              </label>
              <label className="admin-field">
                <span>No. of Days Present</span>
                <input type="number" min="0" step="1" value={firstQuarterReport.daysPresent !== undefined ? firstQuarterReport.daysPresent : ""} onChange={(event) => setFirstQuarterReport(current => ({ ...current, daysPresent: event.target.value }))} />
              </label>
              <button className="primary-button" type="submit" disabled={savingFirstQuarter}>{savingFirstQuarter ? "Saving..." : "Save First Quarter Report"}</button>
            </form>
            {firstQuarterMessage && <p className={firstQuarterMessage.includes("successfully") ? "admin-muted" : "admin-error"}>{firstQuarterMessage}</p>}
          </section>

          <section className="details-section">
            <h2>Second Quarter Report</h2>
            <form className="training-form" onSubmit={handleSecondQuarterSave}>
              <label className="admin-field">
                <span>From Date</span>
                <input type="date" value={secondQuarterReport.fromDate ? secondQuarterReport.fromDate.slice(0, 10) : ""} onChange={(event) => setSecondQuarterReport(current => ({ ...current, fromDate: event.target.value }))} />
              </label>
              <label className="admin-field">
                <span>To Date</span>
                <input type="date" value={secondQuarterReport.toDate ? secondQuarterReport.toDate.slice(0, 10) : ""} onChange={(event) => setSecondQuarterReport(current => ({ ...current, toDate: event.target.value }))} />
              </label>
              <label className="admin-field">
                <span>No. of Days Present</span>
                <input type="number" min="0" step="1" value={secondQuarterReport.daysPresent !== undefined ? secondQuarterReport.daysPresent : ""} onChange={(event) => setSecondQuarterReport(current => ({ ...current, daysPresent: event.target.value }))} />
              </label>
              <button className="primary-button" type="submit" disabled={savingSecondQuarter}>{savingSecondQuarter ? "Saving..." : "Save Second Quarter Report"}</button>
            </form>
            {secondQuarterMessage && <p className={secondQuarterMessage.includes("successfully") ? "admin-muted" : "admin-error"}>{secondQuarterMessage}</p>}
          </section>
        </>
      )}

      {approved && (
        <section className="details-section">
          <h2>Upload Documents</h2>
          <p className="admin-muted">
            Upload the filled Declaration Form and Character Certificate as a single PDF file (Upload Form 1 and Form 2 together).<br />
            Maximum allowed file size: 10 MB.
          </p>
          <form
            className="offer-letter-upload-inline"
            onSubmit={handleCompletedUpload}
          >
            <label className="admin-field">
              <span>Upload Form 1 and Form 2 (Single PDF)</span>
              <input
                accept="application/pdf"
                type="file"
                onChange={(event) =>
                  setCompletedFile(event.target.files?.[0] || null)
                }
              />
            </label>
            <button className="primary-button" type="submit">
              Upload PDF
            </button>
          </form>
          {student.completedDocuments?.url && (
            <FileLink
              label="View Uploaded Combined PDF"
              href={student.completedDocuments.url}
            />
          )}
          {uploadMessage && <p className="admin-muted">{uploadMessage}</p>}
        </section>
      )}
    </main>
  );
}

export default StudentDashboard;
